version: '3.9'

services:
  app:
    # build the docker file inside our current directory (.)
    build:
      context: .
      args:
        - DEV=true
    # port mappings - maps 8000 on local to 8000 in docker container
    ports:
      - "8000:8000"
    # mapping directory "app" from local to "app" directory in docker. 
    # This will allow to changes to code be reflected real-time in the running contianer without the need to manually rebuild 
    volumes:
      - ./app:/app
    # default command to be run when using "docker-compose". It can be overwriten
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
    # env vars on how to connect to db
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
    # env vars for initial configuration of database
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
